import Head from 'next/head'
import axios from 'axios';
import Image from 'next/image'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import PizzaList from '../components/PizzaList'
import AddButton from '../components/AddButton';
import { useState } from 'react';
import Add from '../components/Add';


export default function Home({pizzaList,admin}) {
  const[close,setClose] = useState(true);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@400&display=swap" rel="stylesheet"/>
        
      </Head>
      <Features/>
      {
        admin && <AddButton setClose={setClose}/>
      }
      <PizzaList pizzaList={pizzaList}/>
      {!close && <Add setClose={setClose}/>}

     
    </div>
  )
} 
export const getServerSideProps = async(ctx)=>{
  const mycookie = ctx.req?.cookies || " ";
  let admin= false;
  if(mycookie.token===process.env.TOKEN){
    admin= true;
  }
  const res = await axios.get('http://localhost:3000/api/products')
  return{
    props:{
      pizzaList:res.data, 
      admin
    }
  }
}